apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: L2V0Yy9rdWJlcm5ldGVzL3NzbC9jYS5jcnQK
  signerName: example.com/serving
  usages:
  - digital signature
  - key encipherment
  - server auth