apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: as
    
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      etykieta: share80
  template:
    metadata:
      labels:
        etykieta: share80
        name: nginxdeploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
