apiVersion: v1
kind: Service
metadata:
  name: nginxshare
  labels:
    etykieta: test
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    etykieta: test