apiVersion: v1
kind: Service
metadata:
  name: svcfrontendnp
  labels:
    etykieta: share801
spec:
  type: ClusterIP
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    etykieta: share80