apiVersion: v1
kind: Service
metadata:
  name: svcfrontend
  namespace: as
  labels:
    etykieta: share80
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
  #  nodePort: 30080
  selector:
    etykieta: share80