apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autotest
  namespace: as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploytest
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 0.1