apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpatest
  namespace: as
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: ubuntutest
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

  
    
